defmodule RubberDuck.Repo.Migrations.CreateAgentPersistenceTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:provider_performances, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:provider_name, :text, null: false)
      add(:success_count, :bigint, default: 0)
      add(:failure_count, :bigint, default: 0)
      add(:total_duration, :bigint, default: 0)
      add(:total_tokens, :bigint, default: 0)
      add(:quality_sum, :float, default: 0.0)
      add(:last_updated, :utc_datetime, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:agent_state_id, :uuid, null: false)
    end

    create table(:agent_states, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:provider_performances) do
      modify(
        :agent_state_id,
        references(:agent_states,
          column: :id,
          name: "provider_performances_agent_state_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    create unique_index(:provider_performances, [:agent_state_id, :provider_name],
             name: "provider_performances_unique_provider_per_agent_index"
           )

    alter table(:agent_states) do
      add(:agent_name, :text, null: false)
      add(:agent_type, :text, null: false)
      add(:last_checkpoint, :utc_datetime)
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:agent_states, [:agent_name],
             name: "agent_states_unique_agent_name_index"
           )

    create table(:agent_insights, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:insight_type, :text, null: false)
      add(:insights, :map, null: false)
      add(:confidence, :float, null: false)
      add(:applicable_scenarios, {:array, :text}, default: [])
      add(:learned_at, :utc_datetime, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :agent_state_id,
        references(:agent_states,
          column: :id,
          name: "agent_insights_agent_state_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )
    end

    create table(:agent_experiences, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:experience_type, :text, null: false)
      add(:goal, :map)
      add(:result, :map)
      add(:timestamp, :utc_datetime, null: false)
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :agent_state_id,
        references(:agent_states,
          column: :id,
          name: "agent_experiences_agent_state_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        ),
        null: false
      )
    end

    # Add indices for performance
    create index(:agent_experiences, [:agent_state_id, :timestamp])
    create index(:agent_insights, [:agent_state_id, :insight_type])
    create index(:agent_insights, [:learned_at])
  end

  def down do
    drop(index(:agent_insights, [:learned_at]))
    drop(index(:agent_insights, [:agent_state_id, :insight_type]))
    drop(index(:agent_experiences, [:agent_state_id, :timestamp]))
    
    drop(constraint(:agent_experiences, "agent_experiences_agent_state_id_fkey"))

    drop(table(:agent_experiences))

    drop(constraint(:agent_insights, "agent_insights_agent_state_id_fkey"))

    drop(table(:agent_insights))

    drop_if_exists(
      unique_index(:agent_states, [:agent_name], name: "agent_states_unique_agent_name_index")
    )

    alter table(:agent_states) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:metadata)
      remove(:last_checkpoint)
      remove(:agent_type)
      remove(:agent_name)
    end

    drop_if_exists(
      unique_index(:provider_performances, [:agent_state_id, :provider_name],
        name: "provider_performances_unique_provider_per_agent_index"
      )
    )

    drop(constraint(:provider_performances, "provider_performances_agent_state_id_fkey"))

    alter table(:provider_performances) do
      modify(:agent_state_id, :uuid)
    end

    drop(table(:agent_states))

    drop(table(:provider_performances))
  end
end
