defmodule RubberDuck.Repo.Migrations.SimplifyToUsernameOnlyAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove(:confirmed_at)
      remove(:email)
      add(:username, :citext, null: false)
    end

    drop_if_exists(unique_index(:users, [:email], name: "users_unique_email_index"))

    create unique_index(:users, [:username], name: "users_unique_username_index")
  end

  def down do
    drop_if_exists(unique_index(:users, [:username], name: "users_unique_username_index"))

    create unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove(:username)
      add(:email, :citext, null: false)
      add(:confirmed_at, :utc_datetime_usec)
    end
  end
end
