defmodule :"Elixir.RubberDuck.Repo.Migrations.Core-domains" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:prompts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:description, :text)
      add(:template, :text, null: false)
      add(:variables, {:array, :text}, default: [])
      add(:category, :text)
      add(:tags, {:array, :text}, default: [])
      add(:version, :text, null: false, default: "1.0.0")
      add(:is_public, :boolean, null: false, default: false)
      add(:usage_count, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :author_id,
        references(:users,
          column: :id,
          name: "prompts_author_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create table(:projects, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:description, :text)
      add(:language, :text)
      add(:status, :text, null: false, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :owner_id,
        references(:users,
          column: :id,
          name: "projects_owner_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create table(:code_files, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:path, :text, null: false)
      add(:content, :text)
      add(:language, :text)
      add(:size_bytes, :bigint)
      add(:status, :text, null: false, default: "active")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "code_files_project_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create table(:analysis_results, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:analysis_type, :text, null: false)
      add(:summary, :text)
      add(:details, :map)
      add(:score, :decimal)
      add(:suggestions, {:array, :text}, default: [])
      add(:status, :text, null: false, default: "completed")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "analysis_results_project_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :code_file_id,
        references(:code_files,
          column: :id,
          name: "analysis_results_code_file_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :analyzer_id,
        references(:users,
          column: :id,
          name: "analysis_results_analyzer_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:analysis_results, "analysis_results_project_id_fkey"))

    drop(constraint(:analysis_results, "analysis_results_code_file_id_fkey"))

    drop(constraint(:analysis_results, "analysis_results_analyzer_id_fkey"))

    drop(table(:analysis_results))

    drop(constraint(:code_files, "code_files_project_id_fkey"))

    drop(table(:code_files))

    drop(constraint(:projects, "projects_owner_id_fkey"))

    drop(table(:projects))

    drop(constraint(:prompts, "prompts_author_id_fkey"))

    drop(table(:prompts))
  end
end
