defmodule RubberDuck.Repo.Migrations.AddVerdictSystemConfiguration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:security_policies, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:policy_name, :text, null: false)
      add(:policy_type, :text, null: false)
      add(:resource_type, :text, null: false)
      add(:preference_pattern, :text)
      add(:required_permissions, {:array, :text}, default: [])
      add(:required_roles, {:array, :text}, default: [])
      add(:approval_required, :boolean, default: false)
      add(:approval_roles, {:array, :text}, default: [])
      add(:encryption_required, :boolean, default: false)
      add(:audit_level, :text, default: "basic")
      add(:conditions, :map, default: %{})
      add(:priority, :bigint, default: 100)
      add(:active, :boolean, default: true)
      add(:description, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:preference_schema_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version, :text, null: false)
      add(:version_name, :text)
      add(:description, :text)
      add(:migration_required, :boolean, default: false)
      add(:breaking_changes, :boolean, default: false)
      add(:compatibility_matrix, :map, default: %{})
      add(:migration_scripts, {:array, :text}, default: [])
      add(:rollback_scripts, {:array, :text}, default: [])
      add(:data_transformations, :map, default: %{})
      add(:validation_rules, :map, default: %{})
      add(:deprecated, :boolean, default: false)
      add(:deprecation_notice, :text)
      add(:minimum_app_version, :text)
      add(:applied_at, :utc_datetime)
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:audit_logs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:event_type, :text, null: false)
      add(:event_data, :map, null: false)
      add(:user_id, :uuid)
      add(:preference_key, :text)
      add(:action, :text, null: false)
      add(:ip_address, :text)
      add(:user_agent, :text)
      add(:session_id, :text)
      add(:event_id, :text, null: false)
      add(:severity, :text, default: "info")
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:approval_requests, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:request_type, :text, null: false)

      add(
        :requester_id,
        references(:users,
          column: :id,
          name: "approval_requests_requester_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:target_resource_type, :text, null: false)
      add(:target_resource_id, :text)
      add(:preference_key, :text)
      add(:requested_action, :text, null: false)
      add(:current_value, :text)
      add(:requested_value, :text)
      add(:justification, :text, null: false)
      add(:status, :text, default: "pending")
      add(:priority, :text, default: "medium")

      add(
        :approver_id,
        references(:users,
          column: :id,
          name: "approval_requests_approver_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:approval_notes, :text)
      add(:expires_at, :utc_datetime)
      add(:approved_at, :utc_datetime)
      add(:metadata, :map, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(constraint(:approval_requests, "approval_requests_requester_id_fkey"))

    drop(constraint(:approval_requests, "approval_requests_approver_id_fkey"))

    drop(table(:approval_requests))

    drop(table(:audit_logs))

    drop(table(:preference_schema_versions))

    drop(table(:security_policies))
  end
end
